Add default training pipeline
WorldCereal/worldcereal-classification pull request #184
Opened 2024-10-14 16:32 UTC by kvantricht

2024-10-15 08:49 UTC, jdegerickx commented on scripts/spark/train_catboost.py
> +        model = CatBoostClassifier(
should these model settings be configurable?

2024-10-15 08:56 UTC, jdegerickx commented on src/worldcereal/train/__init__.py
all this filtering of reference datasets and filtering of samples based on rules does not feel generic.
It's also very much tuned to Phase I extractions.
We should probably get rid of this at some point?
Maybe even have a separate repository where we train the global models?

2024-10-15 08:59 UTC, jdegerickx requested changes
main comment is whether we really want to commit all this Phase I related cleaning of datasets to this repository?
I guess in the end all default models will be trained based on Phase II RDM samples and extractions.
So perhaps training of global models should (for now) be done in a separate repository, where we import functionality from worldcereal-classification?
Just a suggestion...

2024-10-15 08:59 UTC, kvantricht commented on src/worldcereal/train/__init__.py
At some point, yes maybe, but this how the model is currently trained so we need to be transparent. I agree that these methods need to evolve in the coming month.

2025-08-22 06:18 UTC, kvantricht commented
Closing as no longer relevant.

2025-08-22 06:18 UTC, closed without merging