234-refactor-point-extractions
WorldCereal/worldcereal-classification pull request #235
Opened 2024-12-18 14:41 UTC by kvantricht

2025-01-08 15:25 UTC, VincentVerelst requested changes

2025-01-08 15:25 UTC, VincentVerelst commented on scripts/extractions/extract.py
> +    input_df = input_df[input_df["extract"] >= extract_value].copy()
Just for my information, was there a change in extract flag convention that prompted this change in the code?

2025-01-08 15:25 UTC, VincentVerelst commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
See my comment below. You can already add the `start_date` and `end_date` in the FeatureCollection that is created in this line to automatically have these columns in your final output parquet.

2025-01-08 16:07 UTC, kvantricht commented on scripts/extractions/extract.py
> +    input_df = input_df[input_df["extract"] >= extract_value].copy()
it was in principle never supposed to be just binary. We aimed this to be something that includes (in the future) a priority depending on its value. To be on the safe side, this now extracts everything that is not 0.

2025-01-08 16:11 UTC, kvantricht commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
> +        gdf["lon"] = gdf.geometry.x
I don't understand this. A job can contain multiple points. `geometry` at that point is a `FeatureCollection`. How can I set there point-specific lat/lon attributes for the dataframe resulting from `aggregate_spatial`?

2025-01-08 16:14 UTC, kvantricht commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
as you can see, it is already set here too, because this is where we get temporal information for filtering collections from. So maybe I should test if indeed by doing this it's now preserved in the resulting dataframe, as before it was not the case.

2025-01-08 16:22 UTC, VincentVerelst commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
I'm sorry for the confusion:

- Only properties of features in the FeatureCollection (`job_to_json()`) in the `geometry` column will be present in the final output geoparquet
- This is because this FeatureCollection is passed to `aggregate_spatial`
- In the code `job` is a `geopandas.GeoDataFrame`. So you first need to add `lat`, `lon`, `start_date` and `end_date` columns to `job` and then convert it to a FeatureCollection.

2025-01-09 10:35 UTC, kvantricht commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
Now I got it. Is the new commit what you mean?

2025-01-09 10:39 UTC, VincentVerelst commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
Did you push the commit already?

2025-01-09 10:42 UTC, kvantricht commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
:facepalm: I did now

2025-01-09 10:47 UTC, VincentVerelst commented on scripts/extractions/point_extractions/extract_point_worldcereal.py
>              "geometry": job.to_json(),
Aha I see it now, indeed that's what I meant :)

2025-01-09 10:47 UTC, VincentVerelst approved these changes

2025-01-09 10:52 UTC, merged