demonstration on how to use cropland extent udp
WorldCereal/worldcereal-classification pull request #238
Opened 2024-12-18 16:40 UTC by jdegerickx

I would suggest to add a script that documents the use of the crop extent UDP.
This script should be extended by @VincentVerelst, to also showcase how to override the default CRS of the output products.

2025-02-17 08:37 UTC, kvantricht reviewed
UDPs will now be added to repo (separate PR). What is needed for this older one then?

2025-02-17 09:13 UTC, jdegerickx commented
I guess once UDP's are added to the repo in the other PR, this PR and branch can be deleted?

2025-02-19 16:31 UTC, jdegerickx commented
@VincentVerelst, would be nice if we could finalize this PR now that the UDP's are in our repo.
Could you check the cropland UDP script and make sure it is fully up-to-date?
Would be nice if we can show in this script what the parameters are that you as a user can play with. Not sure I captured them all at the moment

2025-02-19 16:46 UTC, VincentVerelst requested changes

2025-02-19 16:46 UTC, VincentVerelst commented on scripts/inference/cropland_mapping_udp.py
> +    namespace="https://raw.githubusercontent.com/ESA-APEx/apex_algorithms/refs/heads/main/openeo_udp/worldcereal_crop_extent.json",
The UDPs have been removed from APEx and added to this repo. The latest version URL is: https://github.com/WorldCereal/worldcereal-classification/blob/worldcereal_crop_extent_v1.0.1/src/worldcereal/udp/worldcereal_crop_extent.json

For future reference: you can find the latest UDP by looking at the tags in this repository and opening the newest version (in this case: `worldereal_crop_extent_v1.0.1`). The older ones will also always keep existing by the way, so your code won't break each time we update the UDP.

2025-02-19 16:46 UTC, VincentVerelst commented on scripts/inference/cropland_mapping_udp.py
> +    job_options=JOB_OPTIONS,
With the latest new updates in openEO, `job_options` don't have be set explicitly anymore. They are already embedded in the UDP. It's of course still possible, in case you want to overwrite some settings, like memory for example.

For demonstration purposes, it might be nice to leave some of them in (like `executor-memory`, `python-memory`), but mention that they are optional. Other job options like `udf-dependency-archives` are things users shouldn't have to worry about anymore.

2025-02-21 17:34 UTC, jdegerickx commented
@VincentVerelst, is there a particular reason why we need to go through openeo Federation backend?
Normal CDSE backend also works?

2025-02-21 17:40 UTC, jdegerickx commented
@VincentVerelst, this doesn't seem to work...
![image](https://github.com/user-attachments/assets/5aa69758-f55b-4184-ba6e-bb1376e4291c)

2025-02-24 16:33 UTC, VincentVerelst commented
@jdegerickx ,

- No, using the normal CDSE backend is indeed also fine. We're just pushing the openeofed backend as good practice, but for WorldCereal there should be no reason to just use CDSE 
- For the namespace you need to provide the raw github URL (this is the URL which only shows the raw content, not the full Github page: https://raw.githubusercontent.com/WorldCereal/worldcereal-classification/refs/tags/worldcereal_crop_extent_v1.0.1/src/worldcereal/udp/worldcereal_crop_extent.json

Let me know if that works!

2025-02-25 09:59 UTC, jdegerickx commented
> @jdegerickx ,
> 
> * No, using the normal CDSE backend is indeed also fine. We're just pushing the openeofed backend as good practice, but for WorldCereal there should be no reason to not just use CDSE
> * For the namespace you need to provide the raw github URL (this is the URL which only shows the raw content, not the full Github page: https://raw.githubusercontent.com/WorldCereal/worldcereal-classification/refs/tags/worldcereal_crop_extent_v1.0.1/src/worldcereal/udp/worldcereal_crop_extent.json
> 
> Let me know if that works!

Yes, works now, thanks!
@kvantricht, I tested the UDP and everything seems to work as expected.
Can you check and approve this PR?

2025-02-25 10:05 UTC, kvantricht approved these changes

2025-02-25 11:13 UTC, VincentVerelst approved these changes

2025-02-25 11:14 UTC, merged